version: '3'

services:
  perf_ws:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        DISTRO_VER: ${DISTRO_VER}
    image: 'i_perf_ws'
    container_name: 'c_perf_ws'
    working_dir: '/workdir'
    tty: true
    volumes:
      - ./workdir:/workdir
      - /sys/kernel/debug:/sys/kernel/debug
    # devices:
    #   - /dev/nvme0n1:/dev/nvme0n1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    pid: "host"